# Apply external calibration results to input calexps?
config.makeCoaddTempExp.doApplyExternalPhotoCalib=False
config.makeCoaddTempExp.doApplyExternalSkyWcs=False
config.makeCoaddTempExp.doApplySkyCorr=False

config.assembleCoadd.doApplyExternalPhotoCalib=False
config.assembleCoadd.doApplyExternalSkyWcs=False
config.assembleCoadd.assembleStaticSkyModel.doApplyExternalPhotoCalib=False
config.assembleCoadd.assembleStaticSkyModel.doApplyExternalSkyWcs=False

config.assembleCoadd.doAttachTransmissionCurve=False
